/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
        "colors": {
            "on-tertiary-container": "#0560cb",
            "primary": "#ffffff",
            "on-surface": "#e5e2e1",
            "on-surface-variant": "#c4c7c8",
            "secondary-container": "#0065b0",
            "on-error": "#690005",
            "tertiary-fixed-dim": "#adc6ff",
            "secondary": "#a1c9ff",
            "on-secondary-fixed-variant": "#004880",
            "secondary-fixed-dim": "#a1c9ff",
            "outline": "#8e9192",
            "secondary-fixed": "#d2e4ff",
            "on-secondary-container": "#cfe2ff",
            "surface-container-high": "#2a2a2a",
            "tertiary": "#ffffff",
            "surface-container": "#201f1f",
            "surface-container-lowest": "#0e0e0e",
            "outline-variant": "#444748",
            "primary-fixed-dim": "#c6c6c7",
            "surface-bright": "#3a3939",
            "on-tertiary": "#002e69",
            "inverse-primary": "#5d5f5f",
            "surface-container-highest": "#353434",
            "surface": "#141313",
            "on-primary-fixed": "#1a1c1c",
            "primary-container": "#e2e2e2",
            "on-primary": "#2f3131",
            "error": "#ffb4ab",
            "background": "#141313",
            "error-container": "#93000a",
            "on-primary-container": "#636565",
            "surface-tint": "#c6c6c7",
            "surface-dim": "#141313",
            "inverse-on-surface": "#313030",
            "tertiary-container": "#d8e2ff",
            "inverse-surface": "#e5e2e1",
            "on-error-container": "#ffdad6",
            "surface-variant": "#353434",
            "surface-container-low": "#1c1b1b",
            "on-tertiary-fixed": "#001a41",
            "on-tertiary-fixed-variant": "#004494",
            "on-secondary": "#00325a",
            "on-background": "#e5e2e1",
            "primary-fixed": "#e2e2e2",
            "tertiary-fixed": "#d8e2ff",
            "on-secondary-fixed": "#001c38",
            "on-primary-fixed-variant": "#454747"
        },
        "borderRadius": {
            "DEFAULT": "0px",
            "lg": "0px",
            "xl": "0px",
            "full": "9999px"
        },
        "spacing": {
            "stack-lg": "48px",
            "stack-xl": "96px",
            "stack-sm": "12px",
            "stack-xs": "4px",
            "gutter": "24px",
            "stack-md": "24px",
            "inset-lg": "24px",
            "margin-page": "64px",
            "inset-md": "16px"
        },
        "fontFamily": {
            "body-sm": ["Inter", "sans-serif"],
            "body-md": ["Inter", "sans-serif"],
            "display": ["Inter", "sans-serif"],
            "label-md": ["Inter", "sans-serif"],
            "body-lg": ["Inter", "sans-serif"],
            "label-lg": ["Inter", "sans-serif"],
            "headline-md": ["Inter", "sans-serif"],
            "headline-lg": ["Inter", "sans-serif"],
            "headline-sm": ["Inter", "sans-serif"]
        },
        "fontSize": {
            "body-sm": ["14px", {"lineHeight": "1.5", "letterSpacing": "0em", "fontWeight": "300"}],
            "body-md": ["16px", {"lineHeight": "1.6", "letterSpacing": "0em", "fontWeight": "300"}],
            "display": ["72px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700"}],
            "label-md": ["12px", {"lineHeight": "1.0", "letterSpacing": "0.15em", "fontWeight": "700"}],
            "body-lg": ["18px", {"lineHeight": "1.6", "letterSpacing": "0em", "fontWeight": "300"}],
            "label-lg": ["14px", {"lineHeight": "1.0", "letterSpacing": "0.1em", "fontWeight": "700"}],
            "headline-md": ["32px", {"lineHeight": "1.2", "letterSpacing": "0em", "fontWeight": "700"}],
            "headline-lg": ["48px", {"lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "700"}],
            "headline-sm": ["20px", {"lineHeight": "1.4", "letterSpacing": "0.02em", "fontWeight": "700"}]
        }
    },
  },
  plugins: [],
};
